version: '3.1'

services:
  mysql-test:
    image: mysql:latest
    container_name: mysql-test
    restart: always
    environment:
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_HOST: '%'
    ports:
      - 3307:3306
    command: ["--bind-address=0.0.0.0"] # Allow connections from any IP address
