apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    tier: frontend
spec:
  ports:
  - name: auth-service
    targetPort: 8080
    port: 8080
  selector:
    app: auth-service
    tier: frontend